config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'home#index'
  get 'home/index'

  get 'welcome', controller: 'home'

  resources :tweets,     only: %i(create)
  resources :users,      only: %i(show)
  resources :followings, only: %i(create destroy)
end

app/models/following.rb
class Following < ActiveRecord::Base
  belongs_to :from, class_name: "User"
  belongs_to :to, class_name: "User"

  validates :from_id, presence: true, uniqueness: { scope: :to }
  validates :to_id, presence: true
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  belongs_to :user
  
  validates :user_id, presence: true
  validates :text, presence: true, length: { maximum: 150 }

  paginates_per 10

  default_scope { order("created_at DESC") }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :tweets, dependent: :destroy
  has_many :following_to, class_name: "Following", foreign_key: "from_id", dependent: :destroy
  has_many :followings, through: :following_to, source: :to
  has_many :followed_from, class_name: "Following", foreign_key: "to_id", dependent: :destroy
  has_many :followers, through: :followed_from, source: :from

  scope :active, -> { Tweet.includes(:user).limit(20).map(&:user).uniq }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/followings_controller.rb
class FollowingsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_following, only: %i(destroy)

  def create
    @following = Following.new(following_params)

    if @following.save
      redirect_to :back, notice: "Following was successfully created."
    else
      redirect_to :back, alert: @following.errors.full_messages.first
    end
  end

  def destroy
    @following.destroy
    redirect_to :back, notice: "Following was successfully destroyed."
  end

  private

  def set_following
    @following = Following.find(params[:id])
  end

  def following_params
    params.require(:following).permit(:to_id).merge(from_id: current_user.id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    unless user_signed_in?
      redirect_to :welcome and return
    end

    @active_users = User.active - [current_user]
    @tweet        = Tweet.new
    @tweets       = Tweet.includes(:user)
                         .where(user: current_user.followings + [current_user])
                         .page(params[:page])
  end

  def welcome
  end

end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :authenticate_user!

  def create
    @tweet = Tweet.new(tweet_params)

    if @tweet.save
      redirect_to :back, notice: "Tweet was successfully created."
    else
      redirect_to :back, alert: @tweet.errors.full_messages.first
    end
  end

  private

  def tweet_params
    params.require(:tweet).permit(:text).merge(user_id: current_user.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: %i(show)

  def show
    @user = User.find(params[:id])
    @user_tweets = Tweet.includes(:user).where(user_id: @user.id).page(params[:page])
    @following = Following.find_or_initialize_by(from_id: current_user, to_id: @user)
  end

  private

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/followings/_button.html.haml
- unless current_user == target_user
  - if following.new_record?
    = form_for following, html: { role: "form" } do |f|
      = f.hidden_field :to_id, value: target_user.id
      = f.submit "Follow", class: "btn btn-primary"
  - else
    = link_to "Unfollow", following_path(following.id), class: "btn btn-danger", method: :delete
    %br

app/views/home/index.html.haml
.row
  .col-md-4
    = render partial: "tweets/form", locals: { tweet: @tweet }
    = render partial: "users/list", locals: { title: "Active users", users: @active_users }
  .col-md-8
    = render partial: "tweets/list", locals: { tweets: @tweets }
    = paginate @tweets

app/views/home/welcome.html.haml
.jumbotron
  %h1 Welcome to Kadaitter
  %p Please sign up or sign in

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Kadaitter
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %nav.navbar.navbar-default(role="navigation")
      .container
        .navbar-header
          %button.navbar-toggle(type="button" data-toggle="collapse" data-target="#navbar_collapse_target")
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          = link_to "Kadaitter", root_path, class: "navbar-brand"
        #navbar_collapse_target.collapse.navbar-collapse
          %ul.nav.navbar-nav.navbar-right
            - if user_signed_in?
              %li.dropdown
                %a.dropdown-toggle(href="#" data-toggle="dropdown")
                  = current_user.email
                  %span.caret
                %ul.dropdown-menu(role="menu")
                  %li
                    = link_to "My page", user_path(current_user.id)
                    = link_to "Sign out", destroy_user_session_path, method: :delete
            - else
              %li
                = link_to "Sign in", new_user_session_path
              %li
                = link_to "Sign up", new_user_registration_path

  .container
    - if notice
      .alert.alert-info.alert-dismissible(role="alert")
        %button.close(type="button" data-dismiss="alert")
          %span(aria-hidden="true") &times;
          %span.sr-only Close
        = notice
    - if alert
      .alert.alert-warning.alert-dismissible(role="alert")
        %button.close(type="button" data-dismiss="alert")
          %span(aria-hidden="true") &times;
          %span.sr-only Close
        = alert
    = yield

app/views/tweets/_form.html.haml
.panel.panel-default
  .panel-heading
    %h4.panel-title New tweet
  .panel-body
    = form_for tweet, html: { role: "form" } do |f|
      .form-group
        = f.label :text, "New tweet", class: "sr-only"
        = f.text_field :text, class: "form-control"
      = f.submit "Tweet", class: "btn btn-primary"

app/views/tweets/_list.html.haml
- tweets.each do |tweet|
  .panel.panel-default
    .panel-heading
      %h4.panel-title
        = link_to tweet.user.email, user_path(tweet.user.id)
        %small= "tweeted #{time_ago_in_words(tweet.created_at)} ago"
    .panel-body
      = tweet.text

app/views/users/_list.html.haml
.panel.panel-default
  .panel-heading
    %h4.panel-title= title
  %ul.list-group
    - users.each do |user|
      %li.list-group-item
        = link_to user.email, user_path(user.id)

app/views/users/show.html.haml
%h2= @user.email

= render partial: "followings/button", locals: { following: @following, target_user: @user }
%br

.row
  .col-md-4
    - if @user.followings.present?
      = render partial: "users/list", locals: { title: "Followings (#{@user.followings.size})", users: @user.followings }
    - if @user.followers.present?
      = render partial: "users/list", locals: { title: "Followers (#{@user.followers.size})", users: @user.followers }

  .col-md-8
    = render partial: "tweets/list", locals: { tweets: @user_tweets }
    = paginate @user_tweets